# Generated by Django 3.0.6 on 2021-03-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=255)),
                ('nascimento', models.DateField()),
            ],
        ),
    ]
