# Generated by Django 3.0.6 on 2021-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateApp', '0002_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
    ]
